### ISSUE TITLE
Hitting reset in `load` mode with a memory config file given dismisses pre-set memory values

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#74]
When hitting the reset key while running a program, all memory cells and accumulators are reset to `null`.  
This is a problem when a memory config file is given with `--memory-config-file` that includes starting values for some memory entries, since those are dismissed.

**Comment by LMH01** [comment]
I'd say that this is not per se a bug but just something that I did not think off, when implementing the memory config feature but I see that this can be seen as a bug and it probably can be counted as one.

I *think* that the fix is not too hard.

It could be fixed by saving the state of the runtime memory before the program is run and this state is restored when the runtime is reset.

**Comment by LMH01** [comment]
has been implemented, will be included in next release.
